import json
import os
import smtplib
from datetime import datetime, timezone
from email.message import EmailMessage
from pathlib import Path
from typing import Any, Dict, List, Optional


ROOT_DIR = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT_DIR / "output"
CLIENTS_DIR = ROOT_DIR / "clients"


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def find_latest_week_dir() -> Path:
    if not OUTPUT_DIR.exists():
        raise RuntimeError(f"Missing output directory: {OUTPUT_DIR}")

    week_dirs = sorted(
        [
            path
            for path in OUTPUT_DIR.iterdir()
            if path.is_dir() and path.name.startswith("20") and "-W" in path.name
        ]
    )

    if not week_dirs:
        raise RuntimeError(f"No week output folders found in {OUTPUT_DIR}")

    return week_dirs[-1]


def load_json(path: Path) -> Optional[Dict[str, Any]]:
    if not path.exists():
        return None

    return json.loads(path.read_text(encoding="utf-8"))


def save_json(path: Path, data: Dict[str, Any]) -> None:
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")


def split_emails(value: str) -> List[str]:
    if not value:
        return []

    raw_items = value.replace(";", ",").split(",")

    return [item.strip() for item in raw_items if item.strip()]


def normalize_recipients(value: Any) -> List[str]:
    if value is None:
        return []

    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]

    if isinstance(value, str):
        return split_emails(value)

    return []


def smtp_config_available() -> bool:
    required = [
        "SMTP_HOST",
        "SMTP_USERNAME",
        "SMTP_PASSWORD",
        "SMTP_FROM_EMAIL",
    ]

    return all(os.getenv(key, "").strip() for key in required)


def get_smtp_port() -> int:
    value = os.getenv("SMTP_PORT", "587").strip()

    try:
        return int(value)
    except ValueError:
        return 587


def load_client_config(client_id: str) -> Dict[str, Any]:
    path = CLIENTS_DIR / f"{client_id}.json"
    data = load_json(path)

    if not data:
        return {}

    return data


def resolve_recipients(client_record: Dict[str, Any]) -> List[str]:
    client_id = str(client_record.get("client_id", "")).strip()
    client_config = load_client_config(client_id)

    # Preferred per-client fields.
    recipients = normalize_recipients(client_config.get("email_recipients"))

    if recipients:
        return recipients

    recipients = normalize_recipients(client_config.get("distribution_emails"))

    if recipients:
        return recipients

    recipients = normalize_recipients(client_config.get("delivery_emails"))

    if recipients:
        return recipients

    # Global override for testing or simple single-inbox delivery.
    recipients = split_emails(os.getenv("PACK_EMAIL_TO", "").strip())

    return recipients


def build_email_body(client: Dict[str, Any], week: str) -> str:
    company_name = client.get("company_name", client.get("client_id", "Client"))
    delivery_status = client.get("delivery_status", "unknown")

    drive_zip_url = client.get("drive_zip_url") or ""
    drive_pdf_url = client.get("drive_pdf_url") or ""
    drive_markdown_url = client.get("drive_markdown_url") or ""
    notion_url = client.get("notion_url") or ""

    lines = [
        f"{company_name} - Weekly Trucking Pack",
        "",
        f"Week: {week}",
        f"Delivery status: {delivery_status}",
        "",
        "Files:",
    ]

    if drive_pdf_url:
        lines.append(f"- PDF: {drive_pdf_url}")

    if drive_markdown_url:
        lines.append(f"- Markdown: {drive_markdown_url}")

    if drive_zip_url:
        lines.append(f"- ZIP package: {drive_zip_url}")

    if notion_url:
        lines.append(f"- Notion page: {notion_url}")

    lines.extend(
        [
            "",
            "Production notes:",
            "- This pack was generated by the weekly trucking content pipeline.",
            "- Content quality guardrails ran before delivery.",
            "- Drive, Notion, webhook, and retry checks are recorded in the production artifact.",
            "",
            "If anything looks off, review the production summary and content quality report in the workflow artifact.",
        ]
    )

    return "\n".join(lines)


def send_email(to_addresses: List[str], subject: str, body: str) -> None:
    host = os.getenv("SMTP_HOST", "").strip()
    port = get_smtp_port()
    username = os.getenv("SMTP_USERNAME", "").strip()
    password = os.getenv("SMTP_PASSWORD", "").strip()
    from_email = os.getenv("SMTP_FROM_EMAIL", "").strip()
    from_name = os.getenv("SMTP_FROM_NAME", "Trucking Pack Automation").strip()

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = f"{from_name} <{from_email}>"
    msg["To"] = ", ".join(to_addresses)
    msg.set_content(body)

    with smtplib.SMTP(host, port, timeout=30) as server:
        server.starttls()
        server.login(username, password)
        server.send_message(msg)


def process_client(client: Dict[str, Any], week: str, email_mode: str) -> bool:
    company_name = client.get("company_name", client.get("client_id", "Client"))
    recipients = resolve_recipients(client)

    client["email_mode"] = email_mode
    client["email_checked_at"] = now_iso()

    if email_mode != "real":
        client["email_sent"] = False
        client["email_status"] = "skipped"
        client["email_error"] = "SMTP credentials missing; email delivery skipped."
        print(f"Email skipped for {company_name}: SMTP credentials missing")
        return False

    if not recipients:
        client["email_sent"] = False
        client["email_status"] = "skipped"
        client["email_error"] = "No email recipients configured."
        print(f"Email skipped for {company_name}: no recipients configured")
        return False

    subject = f"{company_name} Weekly Trucking Pack - {week}"
    body = build_email_body(client, week)

    try:
        send_email(recipients, subject, body)
        client["email_sent"] = True
        client["email_status"] = "sent"
        client["email_sent_at"] = now_iso()
        client["email_recipients"] = recipients
        client["email_error"] = None
        print(f"Email sent for {company_name}: {', '.join(recipients)}")
        return True

    except Exception as exc:
        client["email_sent"] = False
        client["email_status"] = "failed"
        client["email_error"] = str(exc)
        client["email_recipients"] = recipients
        print(f"Email failed for {company_name}: {exc}")
        return False


def main() -> None:
    week_dir = find_latest_week_dir()
    manifest_path = week_dir / "distribution_manifest.json"
    manifest = load_json(manifest_path)

    if not manifest:
        raise RuntimeError(f"Missing distribution manifest: {manifest_path}")

    week = manifest.get("week", week_dir.name)
    clients = manifest.get("clients", [])

    if not clients:
        raise RuntimeError(f"No clients found in manifest: {manifest_path}")

    email_mode = "real" if smtp_config_available() else "skipped"

    sent_count = 0
    failed_count = 0
    skipped_count = 0
    changed_count = 0

    for client in clients:
        before = json.dumps(client, sort_keys=True)
        sent = process_client(client, week, email_mode)
        after = json.dumps(client, sort_keys=True)

        if before != after:
            changed_count += 1

        status = client.get("email_status")

        if sent:
            sent_count += 1
        elif status == "failed":
            failed_count += 1
        else:
            skipped_count += 1

    manifest["email_notifications_completed_at"] = now_iso()
    manifest["email_mode"] = email_mode
    manifest["email_sent_client_count"] = sent_count
    manifest["email_failed_client_count"] = failed_count
    manifest["email_skipped_client_count"] = skipped_count
    manifest["email_changed_client_count"] = changed_count
    manifest["last_updated_at"] = now_iso()

    save_json(manifest_path, manifest)

    print(f"Saved manifest: {manifest_path}")
    print(f"Email mode: {email_mode}")
    print(f"Email sent clients: {sent_count}")
    print(f"Email failed clients: {failed_count}")
    print(f"Email skipped clients: {skipped_count}")
    print(f"Changed client records: {changed_count}")


if __name__ == "__main__":
    main()
